spring:
  datasource: 
    url: jdbc:mysql:///test
    username: root  
    password: root
    
  mvc:
    view:
      prefix: /  
      suffix: .jsp 
      
server:
  port: 8080  
  servlet:
    path: /boot
    session:
      timeout: 10  